import { useState } from 'react';
import { Share2, FileText, Presentation, FileSpreadsheet, Download, Check } from 'lucide-react';

export default function ExportActions({ reportId, token, onShare, shareLink, reportData }) {
  const [exporting, setExporting] = useState('');
  const [copied, setCopied] = useState(false);

  const handleExportPDF = () => {
    setExporting('pdf');
    setTimeout(() => {
      window.print();
      setExporting('');
    }, 100);
  };

  const generateExportContent = (type) => {
    const output = reportData?.outputData;
    if (!output) return;

    const sections = output.sections;
    const score = output.compositeScore;
    const verdict = output.verdict;
    const ideaName = reportData.ideaName || 'Startup Idea';

    let content = '';

    if (type === 'pitch') {
      content = `
<!DOCTYPE html><html><head><meta charset="utf-8"><title>${ideaName} - Pitch Deck</title>
<style>
body{font-family:'Helvetica Neue',sans-serif;margin:0;padding:40px;background:#0a0b10;color:#fff}
.slide{page-break-after:always;min-height:90vh;display:flex;flex-direction:column;justify-content:center;padding:60px}
h1{font-size:48px;margin-bottom:20px;color:#00DF82}
h2{font-size:32px;margin-bottom:16px;color:#00A3FF}
p{font-size:18px;line-height:1.6;color:#94a3b8}
.score{font-size:72px;color:#00DF82;font-weight:bold}
.metric{display:inline-block;margin:10px 20px;text-align:center}
.metric-value{font-size:36px;font-weight:bold;color:#fff}
.metric-label{font-size:14px;color:#94a3b8}
</style></head><body>
<div class="slide"><h1>${ideaName}</h1><p>Startup Validation Report — VentureIQ</p><p>Score: <span class="score">${score}/100</span> | Verdict: ${verdict?.toUpperCase()}</p></div>
<div class="slide"><h2>Problem</h2><p>${sections?.problemAnalysis || ''}</p></div>
<div class="slide"><h2>Market Opportunity</h2><div class="metric"><div class="metric-value">${sections?.marketOpportunity?.tamEstimate || '—'}</div><div class="metric-label">TAM</div></div><div class="metric"><div class="metric-value">${sections?.marketOpportunity?.samEstimate || '—'}</div><div class="metric-label">SAM</div></div><div class="metric"><div class="metric-value">${sections?.marketOpportunity?.somEstimate || '—'}</div><div class="metric-label">SOM</div></div></div>
<div class="slide"><h2>Competition</h2><p>${sections?.competitionAnalysis?.positioning || ''}</p></div>
<div class="slide"><h2>MVP Strategy</h2><p>${sections?.mvpSuggestions || ''}</p></div>
<div class="slide"><h2>Final Verdict</h2><p>${sections?.finalVerdict || ''}</p></div>
</body></html>`;
    } else if (type === 'memo') {
      content = `
<!DOCTYPE html><html><head><meta charset="utf-8"><title>${ideaName} - Investor Memo</title>
<style>
body{font-family:'Helvetica Neue',sans-serif;max-width:800px;margin:0 auto;padding:40px;background:#fff;color:#1a1a1a}
h1{font-size:28px;border-bottom:2px solid #00DF82;padding-bottom:10px}
h2{font-size:18px;color:#333;margin-top:30px}
p{font-size:14px;line-height:1.8;color:#555}
.header{display:flex;justify-content:space-between;align-items:center}
.score-box{background:#f0fdf4;border:1px solid #00DF82;padding:15px 25px;border-radius:8px;text-align:center}
.score-box .value{font-size:36px;font-weight:bold;color:#00DF82}
</style></head><body>
<div class="header"><h1>${ideaName}</h1><div class="score-box"><div class="value">${score}/100</div><div>Score</div></div></div>
<h2>Executive Summary</h2><p>${sections?.ideaSummary || ''}</p>
<h2>Market Opportunity</h2><p>TAM: ${sections?.marketOpportunity?.tamEstimate || '—'} | SAM: ${sections?.marketOpportunity?.samEstimate || '—'} | SOM: ${sections?.marketOpportunity?.somEstimate || '—'}</p><p>${sections?.marketOpportunity?.narrative || ''}</p>
<h2>Competition</h2><p>${sections?.competitionAnalysis?.positioning || ''}</p>
<h2>Risks</h2>${sections?.risks?.map((r) => `<p><strong>${r.severity.toUpperCase()}:</strong> ${r.risk} → ${r.mitigation}</p>`).join('') || ''}
<h2>Funding Recommendation</h2><p>${sections?.fundingFit || ''}</p>
<h2>Verdict</h2><p>${sections?.finalVerdict || ''}</p>
<hr><p style="font-size:12px;color:#999">Generated by VentureIQ AI — ${new Date().toLocaleDateString()}</p>
</body></html>`;
    } else {
      content = `
<!DOCTYPE html><html><head><meta charset="utf-8"><title>${ideaName} - Business Plan</title>
<style>
body{font-family:'Helvetica Neue',sans-serif;max-width:900px;margin:0 auto;padding:40px;background:#fff;color:#1a1a1a}
h1{font-size:32px;color:#0a0b10}
h2{font-size:20px;color:#333;margin-top:30px;border-left:3px solid #00DF82;padding-left:10px}
p{font-size:14px;line-height:1.8;color:#555}
</style></head><body>
<h1>${ideaName} — Business Plan</h1>
<h2>Idea Summary</h2><p>${sections?.ideaSummary || ''}</p>
<h2>Problem Analysis</h2><p>${sections?.problemAnalysis || ''}</p>
<h2>Target Audience</h2><p>${sections?.targetAudienceAnalysis || ''}</p>
<h2>Market Opportunity</h2><p>${sections?.marketOpportunity?.narrative || ''}</p>
<h2>Competition</h2><p>${sections?.competitionAnalysis?.positioning || ''}</p>
<h2>MVP Strategy</h2><p>${sections?.mvpSuggestions || ''}</p>
<h2>Risks & Mitigation</h2>${sections?.risks?.map((r) => `<p><strong>[${r.severity.toUpperCase()}]</strong> ${r.risk}: ${r.mitigation}</p>`).join('') || ''}
<h2>Recommendations</h2>${sections?.recommendations?.map((r) => `<p>${r.priority}. ${r.action} — ${r.reason}</p>`).join('') || ''}
<h2>Funding</h2><p>${sections?.fundingFit || ''}</p>
<h2>30-Day Action Plan</h2>${sections?.actionPlan?.map((w) => `<p><strong>Week ${w.week}: ${w.goal}</strong><br/>${w.tasks?.join(', ')}</p>`).join('') || ''}
<h2>Final Verdict</h2><p>${sections?.finalVerdict || ''}</p>
<hr><p style="font-size:12px;color:#999">Generated by VentureIQ AI — ${new Date().toLocaleDateString()}</p>
</body></html>`;
    }

    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${ideaName.replace(/\s+/g, '_')}_${type}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShareClick = () => {
    onShare();
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const actions = [
    { label: 'PDF', icon: FileText, onClick: handleExportPDF, id: 'pdf' },
    { label: 'Pitch Deck', icon: Presentation, onClick: () => generateExportContent('pitch'), id: 'pitch' },
    { label: 'Investor Memo', icon: FileSpreadsheet, onClick: () => generateExportContent('memo'), id: 'memo' },
    { label: 'Business Plan', icon: Download, onClick: () => generateExportContent('plan'), id: 'plan' },
  ];

  return (
    <div className="flex flex-wrap gap-2 no-print">
      {actions.map(action => (
        <button
          key={action.id}
          onClick={action.onClick}
          disabled={exporting === action.id}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-card border border-border text-xs hover:bg-accent/30 transition-colors disabled:opacity-50"
        >
          <action.icon className="w-3.5 h-3.5" />
          {action.label}
        </button>
      ))}
      <button
        onClick={handleShareClick}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 border border-primary/30 text-xs text-primary hover:bg-primary/20 transition-colors"
      >
        {copied ? <Check className="w-3.5 h-3.5" /> : <Share2 className="w-3.5 h-3.5" />}
        {copied ? 'Copied!' : 'Share'}
      </button>
    </div>
  );
}
